spring:
  application:
    name: demo
  mail:
    host: smtp.mailgun.org
    port: 587
    username: ${MAILGUN_USER_NAME}
    password: ${MAILGUN_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

github:
  repo:
    owner: MykaelXiong
    name: personal-note
    branch: main
  token: ${GITHUB_TOKEN}

chatgpt:
  email: placeholder
  password: placeholder

keybr:
  auth:
    google:
      email: ${KEYBR_GOOGLE_EMAIL}
      password: ${KEYBR_GOOGLE_PASSWORD}


screenshot:
  path: "./screenshots"

chrome:
  binary: ""
  driver: ""
  settings:
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    additionalArgs:
      - "--disable-blink-features=AutomationControlled"
      - "--disable-extensions"
      - "--no-sandbox"
      - "--disable-dev-shm-usage"
      - "--window-size=1920,1080"
      - "--disable-gpu"
      - "--ignore-certificate-errors"
      - "--allow-running-insecure-content"
      - "--disable-web-security"
      - "--lang=en-US,en;q=0.9"
    stealthArgs:
      - "--remote-debugging-port=9222"
      - "--disable-setuid-sandbox"
      - "--disable-gpu-sandbox"

# =======================================
# Linux profile overrides
# =======================================
---
spring:
  config:
    activate:
      on-profile: linux
chrome:
  binary: "/usr/bin/chromium-browser"
  driver: "/usr/bin/chromedriver"

# =======================================
# Windows profile overrides
# =======================================
---
spring:
  config:
    activate:
      on-profile: windows
chrome:
  binary:
  driver: